#pragma once

#include "driver/gpio.h"
#include "i2c_device.h"
#include "esp_log.h"

#if CONFIG_SOFTWARE_ESP_WIFI_SUPPORT
#include "wifi.h"
#endif

#ifdef CONFIG_SOFTWARE_ESP_LCD_UI_SUPPORT
#ifdef CONFIG_SOFTWARE_MODEL_SSD1306_I2C
#include "i2c_ssd1306.h"
#endif
#endif

#if CONFIG_SOFTWARE_UNIT_ENV2_SUPPORT
#include "sht3x.h"
#endif

#if CONFIG_SOFTWARE_UNIT_SK6812_SUPPORT
#include "sk6812.h"
#endif

#if CONFIG_SOFTWARE_UNIT_RTC_SUPPORT
#if CONFIG_SOFTWARE_MODEL_RTC_PCF8563
#include "pcf8563.h"
#elif CONFIG_SOFTWARE_MODEL_RTC_RX8900
#include "rx8900.h"
#else
#endif
#endif

#if ( CONFIG_SOFTWARE_UNIT_4DIGIT_DISPLAY_SUPPORT || CONFIG_SOFTWARE_UNIT_6DIGIT_DISPLAY_SUPPORT )
#include "tm1637.h"

#ifdef CONFIG_SOFTWARE_UNIT_4DIGIT_DISPLAY_SUPPORT
#define DIGIT_COUNT 4
#elif CONFIG_SOFTWARE_UNIT_6DIGIT_DISPLAY_SUPPORT
#define DIGIT_COUNT 6
#else
#define DIGIT_COUNT 1
#endif

#endif

#if CONFIG_SOFTWARE_UNIT_LED_SUPPORT
#include "led.h"
#endif

#if CONFIG_SOFTWARE_UNIT_BUTTON_SUPPORT
#include "button.h"
#endif

#if CONFIG_SOFTWARE_I2C_RTC_RX8900_SUPPORT
#include "rx8900.h"
#endif

#if CONFIG_SOFTWARE_I2C_LCD_ST7032_SUPPORT
#include "st7032.h"
#endif

#ifdef CONFIG_SOFTWARE_BUZZER_SUPPORT
#include "buzzer.h"
#endif

// ESP Model
#define PORT_I2C_STANDARD_BAUD 400000
#define PORT_LEVEL_HIGH 1
#define PORT_LEVEL_LOW  0

#if CONFIG_HARDWARE_MODEL_EPS32S3
#define PORT_D1_PIN GPIO_NUM_1
#define PORT_D2_PIN GPIO_NUM_2
#define PORT_D3_PIN GPIO_NUM_3
#define PORT_D4_PIN GPIO_NUM_4
#define PORT_D5_PIN GPIO_NUM_5
#define PORT_D6_PIN GPIO_NUM_6
#define PORT_D7_PIN GPIO_NUM_7
#define PORT_D8_PIN GPIO_NUM_8
#define PORT_D9_PIN GPIO_NUM_9
#define PORT_D10_PIN GPIO_NUM_10
#define PORT_D11_PIN GPIO_NUM_11
#define PORT_D12_PIN GPIO_NUM_12
#define PORT_D13_PIN GPIO_NUM_13
#define PORT_D14_PIN GPIO_NUM_14
#define PORT_D15_PIN GPIO_NUM_15
#define PORT_D16_PIN GPIO_NUM_16
#define PORT_D17_PIN GPIO_NUM_17
#define PORT_D18_PIN GPIO_NUM_18
#define PORT_D21_PIN GPIO_NUM_21
#define PORT_D38_PIN GPIO_NUM_38
#define PORT_D39_PIN GPIO_NUM_39
#define PORT_D40_PIN GPIO_NUM_40
#define PORT_D41_PIN GPIO_NUM_41
#define PORT_D42_PIN GPIO_NUM_42
#define PORT_D45_PIN GPIO_NUM_45
#define PORT_D46_PIN GPIO_NUM_46
#define PORT_D47_PIN GPIO_NUM_47
#define PORT_D48_PIN GPIO_NUM_48
#define PORT_SDA_PIN GPIO_NUM_1
#define PORT_SCL_PIN GPIO_NUM_2
#define PORT_TX_PIN GPIO_NUM_43
#define PORT_RX_PIN GPIO_NUM_44
#define PORT_LCD_RST_PIN GPIO_NUM_39
#define PORT_MOSI_PIN_PIN GPIO_NUM_40
#define PORT_MISO_PIN GPIO_NUM_41
#define PORT_SCK_PIN GPIO_NUM_42
#define PORT_LCD_CS_PIN GPIO_NUM_45
#define PORT_LCD_BL_PIN GPIO_NUM_46

#elif CONFIG_HARDWARE_MODEL_XIAO_EPS32C3
#define PORT_D0_PIN GPIO_NUM_2
#define PORT_D1_PIN GPIO_NUM_3
#define PORT_D2_PIN GPIO_NUM_4
#define PORT_D3_PIN GPIO_NUM_5
#define PORT_D4_PIN GPIO_NUM_6
#define PORT_D5_PIN GPIO_NUM_7
#define PORT_D6_PIN GPIO_NUM_21
#define PORT_D7_PIN GPIO_NUM_20
#define PORT_D8_PIN GPIO_NUM_8
#define PORT_D9_PIN GPIO_NUM_9
#define PORT_D10_PIN GPIO_NUM_10
#define PORT_A0_PIN GPIO_NUM_2
#define PORT_A1_PIN GPIO_NUM_3
#define PORT_A2_PIN GPIO_NUM_4
#define PORT_A3_PIN GPIO_NUM_5
#define PORT_SDA_PIN GPIO_NUM_6
#define PORT_SCL_PIN GPIO_NUM_7
#define PORT_TX_PIN GPIO_NUM_21
#define PORT_RX_PIN GPIO_NUM_20
#define PORT_SCK_PIN GPIO_NUM_8
#define PORT_MISO_PIN GPIO_NUM_9
#define PORT_MOSI_PIN GPIO_NUM_10

#endif